// @sumrak/schema — Zod schemas + TS types for content packs, the content-repo
// manifest, and the backup envelope. Single source of truth shared by the app
// importer (T03), content sync (T07), and the authoring pipeline (T08).
export {
  CefrLevelSchema,
  LocalizedTextSchema,
  PackTypeSchema,
  RelativePathSchema,
  StableIdSchema,
  type CefrLevel,
  type LocalizedText,
  type PackType,
} from './common';
export {
  SentenceSchema,
  TokenSchema,
  WordStampSchema,
  reconstructSentenceRu,
  type Sentence,
  type Token,
  type WordStamp,
} from './sentence';
export {
  CharacterSchema,
  ChoiceSchema,
  DialogueNodeSchema,
  DialogueSchema,
  EndingSchema,
  EndingToneSchema,
  MAX_CHOICES_PER_NODE,
  MAX_DIALOGUE_NODES,
  MIN_CHOICES_PER_NODE,
  NodeAudioSchema,
  PLAYER_CHARACTER_ID,
  analyzeDialogueGraph,
  type Character,
  type Choice,
  type Dialogue,
  type DialogueGraphAnalysis,
  type DialogueGraphInput,
  type DialogueNode,
  type Ending,
  type EndingTone,
  type NodeAudio,
} from './dialogue';
export {
  ExpectationSchema,
  GlossaryEntrySchema,
  LineAudioSchema,
  MOUTH_TRACK_STEP_MS,
  NUDGE_KINDS,
  NUMBER_BRANCH_KEY,
  NudgeKindSchema,
  NudgeSchema,
  PortraitSchema,
  RetrySchema,
  SCENARIO_MAX_BRANCHES,
  SCENARIO_MAX_LINES_PER_TURN,
  SCENARIO_MAX_TURNS,
  ScenarioCharacterSchema,
  ScenarioLineSchema,
  ScenarioRoleSchema,
  ScenarioSceneSchema,
  ScenarioSchema,
  ScenarioTurnSchema,
  SlotOptionSchema,
  SlotSchema,
  TurnNextSchema,
  scenarioGraphInput,
  scenarioLines,
  slotBranchKeys,
  slotFormIssue,
  type Expectation,
  type GlossaryEntry,
  type LineAudio,
  type Nudge,
  type NudgeKind,
  type Portrait,
  type Retry,
  type Scenario,
  type ScenarioCharacter,
  type ScenarioLine,
  type ScenarioLineKind,
  type ScenarioLineRef,
  type ScenarioRole,
  type ScenarioScene,
  type ScenarioTurn,
  type Slot,
  type SlotOption,
  type TurnNext,
} from './scenario';
export {
  ChoiceItemSchema,
  EXAM_SUBTEST_KINDS,
  ExamItemSchema,
  ExamPartSchema,
  ExamSchema,
  ExamSubtestKindSchema,
  ExamSubtestSchema,
  OBJECTIVE_SUBTEST_KINDS,
  SpeakingMonologueItemSchema,
  SpeakingTurnItemSchema,
  StoryRefSchema,
  TORFL_A1_SHAPE,
  TORFL_A2_SHAPE,
  TORFL_SHAPES,
  TORFL_SUBTEST_ORDER,
  type TorflOfficialShape,
  TypedItemSchema,
  WritingItemSchema,
  countStemGaps,
  examStoryRefs,
  itemPoints,
  officialShapeIssues,
  resolveItemAudio,
  type ChoiceItem,
  type Exam,
  type ExamItem,
  type ExamItemKind,
  type ExamPart,
  type ExamRefField,
  type ExamStoryRef,
  type ExamSubtest,
  type ExamSubtestKind,
  type SpeakingMonologueItem,
  type SpeakingTurnItem,
  type StoryRef,
  type TypedItem,
  type WritingItem,
} from './exam';
export {
  LemmaListSchema,
  ReferenceLemmaSchema,
  referenceLemmaKey,
  type LemmaList,
  type ReferenceLemma,
} from './reference';
export {
  AudioTrackSchema,
  ExerciseSpecSchema,
  JournalPromptSchema,
  LessonSchema,
  PackSchema,
  PackThemeSchema,
  StorySchema,
  StorySourceSchema,
  type AudioTrack,
  type ExerciseSpec,
  type JournalPrompt,
  type Lesson,
  type Pack,
  type PackTheme,
  type Story,
  type StorySource,
} from './pack';
export {
  ManifestEntrySchema,
  ManifestFileSchema,
  ManifestSchema,
  type Manifest,
  type ManifestEntry,
  type ManifestFile,
} from './manifest';
export {
  ModelKindSchema,
  ModelsManifestEntrySchema,
  ModelsManifestSchema,
  type ModelKind,
  type ModelsManifest,
  type ModelsManifestEntry,
} from './models-manifest';
export { BackupEnvelopeSchema, type BackupEnvelope } from './backup';
export {
  SchemaValidationError,
  parseBackupEnvelope,
  parseManifest,
  parseModelsManifest,
  parsePack,
  safeParseBackupEnvelope,
  safeParseManifest,
  safeParseModelsManifest,
  safeParsePack,
  toSchemaIssues,
  type ParseResult,
  type SchemaIssue,
} from './parse';
