import { parseBackupEnvelope, type BackupEnvelope } from '@sumrak/schema';
import { gcm } from '@noble/ciphers/aes.js';
import { pbkdf2Async } from '@noble/hashes/pbkdf2.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { gunzipSync, gzipSync, strFromU8, strToU8 } from 'fflate';

import { base64ToBytes, bytesToBase64 } from '@/lib/base64';

import { BackupError } from './errors';

/**
 * Pure crypto core for backup snapshots (T20; T21's syncd target reuses this
 * unchanged). Pipeline: payload JSON → gzip → AES-256-GCM → base64 inside
 * the envelope (schema in @sumrak/schema — self-describing: salt + iteration
 * count ride in every file so a fresh device needs only the passphrase).
 *
 * Everything here is deterministic given its inputs: randomness (salt, IV)
 * is generated by the caller (expo-crypto on device, webcrypto in tests) so
 * this module runs identically under Hermes and vitest.
 *
 * KDF: PBKDF2-HMAC-SHA256 via @noble/hashes (audited, pure JS — chosen over
 * a native crypto module to keep disaster-recovery code dependency-light and
 * unit-testable; see ticket notes for the iteration-count reasoning).
 * Passphrases are NFC-normalized before encoding, so a passphrase typed on a
 * different keyboard (composed vs decomposed ё…) still derives the same key.
 */

export const KDF_ITERATIONS_DEFAULT = 210_000;
export const KDF_SALT_BYTES = 16;
export const GCM_IV_BYTES = 12;
const KEY_BYTES = 32;

export async function deriveBackupKey(
  passphrase: string,
  saltB64: string,
  iterations: number,
): Promise<Uint8Array> {
  const salt = base64ToBytes(saltB64);
  return pbkdf2Async(sha256, strToU8(passphrase.normalize('NFC')), salt, {
    c: iterations,
    dkLen: KEY_BYTES,
  });
}

export interface EncryptParams {
  saltB64: string;
  iterations: number;
  /** Fresh random GCM nonce, GCM_IV_BYTES long — never reuse with the same key. */
  iv: Uint8Array;
  createdAt: Date;
  appVersion?: string;
  /** T63: `'media'` for a scenario media bundle; omitted for snapshots (T20 files carry none). */
  kind?: 'snapshot' | 'media';
}

/** payload JSON string → sealed envelope object (caller serializes/uploads it). */
export function encryptBackupPayload(
  payloadJson: string,
  key: Uint8Array,
  params: EncryptParams,
): BackupEnvelope {
  return encryptBackupBytes(strToU8(payloadJson), key, params);
}

/**
 * Arbitrary bytes → sealed envelope (T63 media bundles ride the same
 * gzip → AES-GCM → base64 pipeline; `kind` says what the plaintext is).
 */
export function encryptBackupBytes(
  plaintext: Uint8Array,
  key: Uint8Array,
  params: EncryptParams,
): BackupEnvelope {
  if (params.iv.length !== GCM_IV_BYTES) throw new BackupError('unknown', 'bad IV length');
  const gzipped = gzipSync(plaintext);
  const ciphertext = gcm(key, params.iv).encrypt(gzipped);
  return {
    format: 'sumrak-backup',
    version: 1,
    createdAt: params.createdAt.toISOString(),
    ...(params.appVersion ? { appVersion: params.appVersion } : {}),
    ...(params.kind ? { kind: params.kind } : {}),
    cipher: {
      alg: 'aes-256-gcm',
      kdf: 'pbkdf2-sha256',
      iterations: params.iterations,
      saltB64: params.saltB64,
      ivB64: bytesToBase64(params.iv),
    },
    payloadB64: bytesToBase64(ciphertext),
  };
}

/** Parse raw file text as an envelope; BackupError('invalid-envelope') when it isn't one. */
export function parseEnvelopeText(text: string): BackupEnvelope {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new BackupError('invalid-envelope', 'not JSON');
  }
  try {
    return parseBackupEnvelope(raw);
  } catch (err) {
    throw new BackupError(
      'invalid-envelope',
      err instanceof Error ? err.message : 'envelope failed validation',
    );
  }
}

/**
 * Envelope + key → payload JSON string. A wrong key and a corrupted
 * ciphertext are indistinguishable (GCM auth tag) — both surface as
 * BackupError('decrypt-failed'), and nothing is ever partially returned.
 */
export function decryptBackupEnvelope(envelope: BackupEnvelope, key: Uint8Array): string {
  if (envelopeKind(envelope) !== 'snapshot') {
    throw new BackupError('invalid-envelope', 'this file is a media bundle, not a snapshot');
  }
  return strFromU8(decryptBackupBytes(envelope, key));
}

/** `kind` with the T20 default: files without the field are snapshots. */
export function envelopeKind(envelope: BackupEnvelope): 'snapshot' | 'media' {
  return envelope.kind ?? 'snapshot';
}

/** Envelope + key → plaintext bytes (any kind; T63 media bundles decrypt through here). */
export function decryptBackupBytes(envelope: BackupEnvelope, key: Uint8Array): Uint8Array {
  let gzipped: Uint8Array;
  try {
    const iv = base64ToBytes(envelope.cipher.ivB64);
    const ciphertext = base64ToBytes(envelope.payloadB64);
    gzipped = gcm(key, iv).decrypt(ciphertext);
  } catch {
    throw new BackupError('decrypt-failed', 'AES-GCM authentication failed');
  }
  try {
    return gunzipSync(gzipped);
  } catch {
    // Authenticated but not gzip — can only mean an incompatible producer.
    throw new BackupError('invalid-envelope', 'decrypted payload is not gzip');
  }
}
